### ISSUE TITLE
Doesn't run. R2016B

### ISSUE THREAD

**Issue by jens120** [AppliedMechanics/AMrotor#1]
First I run InstallChecker.m

Then I run Examples\Simple_Laval\Simulation_Time.m and I get thef following error messages:

```
>> InstallChecker
>> Simulation_Time
Created PlotJanitor....
Error using AMrotorSIM.Rotorsystem
Error: File: Rotorsystem.m Line: 12 Column: 13
Unexpected MATLAB expression.

Error in Simulation_Time (line 20)
r=Rotorsystem(cnfg,'Laval-Rotor'); % Instantiation of class
Rotorsystem
```
 
![Screenshot (127)](https://github.com/AppliedMechanics/AMrotor/assets/49058697/5b873e49-c7c6-481a-b971-a4817501a514)

I don't understand this error on line 12. Could it have something to do with my version of MATLAB? Also I don't have the symbolic toolbox. Can I still use AMrotor?

**Comment by mtkreutz** [comment]
This was changed in 5f60964, when the old undocumented syntax became unsupported by Matlab (https://undocumentedmatlab.com/articles/setting-class-property-types-2)
Please try to use a current version of Matlab, to see if this solves your problem.

The symbolic math toolbox is not required anymore for any functions of in _+AMrotorSIM_. This was changed was just changed in the last commit (5e5d156)

**Comment by jens120** [comment]
hi @mtkreutz ,
thanks for the info. I got it running on Matlab online :)
